import type { NativePanelConfig } from "../schemas/panel.schema";

export const trabalhoEmprego: NativePanelConfig = {
  schemaVersion: 1,
  kind: "native",
  id: "trabalho-emprego",
  title: "Trabalho e Emprego",
  description: "Indicadores do mercado formal de trabalho no município.",
  theme: "Desenvolvimento Econômico",
  tags: ["emprego", "caged", "trabalho"],
  metadata: {
    source: "CAGED / Ministério do Trabalho (dados fictícios)",
    owner: "Equipe de Serviços",
    methodologyNote:
      "Saldo = admissões menos desligamentos, apurado por competência de referência. Os indicadores de resumo e a evolução mensal não são segmentados por sexo ou faixa etária nesta versão do protótipo — selecionar esses filtros pode resultar em ausência de dados.",
  },
  presentation: "default",
  filters: [
    { id: "ano", type: "single-select", label: "Ano", dataField: "ano" },
    { id: "mes", type: "single-select", label: "Mês", dataField: "mes" },
    { id: "sexo", type: "multi-select", label: "Sexo", dataField: "sexo" },
    { id: "faixa_etaria", type: "multi-select", label: "Faixa etária", dataField: "faixaEtaria" },
    { id: "setor", type: "multi-select", label: "Setor econômico", dataField: "setor" },
  ],
  sections: [
    {
      id: "resumo",
      title: "Resumo",
      layout: "grid-4",
      components: [
        {
          id: "saldo",
          type: "indicator-card",
          title: "Saldo de empregos",
          metric: "saldo_empregos",
          format: "integer",
          comparison: "previous-period",
          indicatorId: "saldo_empregos",
        },
        {
          id: "admissoes",
          type: "indicator-card",
          title: "Admissões",
          metric: "admissoes",
          format: "integer",
          comparison: "previous-period",
          indicatorId: "admissoes",
        },
        {
          id: "desligamentos",
          type: "indicator-card",
          title: "Desligamentos",
          metric: "desligamentos",
          format: "integer",
          comparison: "previous-period",
          indicatorId: "desligamentos",
        },
        {
          id: "estoque",
          type: "indicator-card",
          title: "Estoque de vínculos",
          metric: "estoque_vinculos",
          format: "integer",
          comparison: "previous-period",
          indicatorId: "estoque_vinculos",
        },
      ],
    },
    {
      id: "evolucao",
      title: "Evolução",
      layout: "stack",
      components: [
        {
          id: "saldo-tempo",
          type: "time-series",
          title: "Evolução mensal do saldo",
          metric: "saldo_empregos",
          format: "integer",
        },
        {
          id: "por-setor",
          type: "bar-chart",
          title: "Vínculos por setor econômico",
          metric: "estoque_vinculos",
          dimension: "setor",
          orientation: "horizontal",
          sort: "desc",
          format: "integer",
        },
        {
          id: "tab-atividade",
          type: "data-table",
          title: "Vínculos por atividade econômica",
          dataset: "vinculos_por_atividade",
          columns: [
            { field: "atividade", label: "Atividade", type: "text" },
            { field: "vinculos", label: "Vínculos", type: "integer" },
            { field: "variacao", label: "Variação", type: "percent" },
          ],
          limit: 15,
        },
      ],
    },
  ],
};
